language: cpp

before_install:
  # Don't build if the last commit was from travis
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- if [[ "$TRAVIS_COMMIT_MSG" = "$COMMIT_IGNORE_BUILD" ]]; then exit 0 ; fi

  # Configure git
- git config --global user.email "$USER_EMAIL"
- git config --global user.name "$USER_NAME"
- git config --global push.default simple
- git checkout $TRAVIS_BRANCH

install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq

  # Install valgrind
- sudo apt-get install -qq valgrind

  # Install g++
- if [ "$CXX" = "g++" ]; then
    sudo apt-get install -qq g++-4.8;
    export CXX="g++-4.8" CC="gcc-4.8";
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
  fi

  # Install clang
- if [ "$CXX" = "clang++" ]; then
    sudo apt-get install -qq clang;
    export CXX="clang++" CC="clang";
    sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 90;
    sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 90;
  fi

  # Install Biicode
- wget -O bii-ubuntu64.deb http://www.biicode.com/downloads/latest/ubuntu64
- "(sudo dpkg -i bii-ubuntu64.deb) && sudo apt-get -f install"
- bii --version
- bii user $USER -p $BII_PASSWORD
- rm bii-ubuntu64.deb

  # Install CMake
- wget http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
- tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz
- sudo cp -fR cmake-3.3.2-Linux-x86_64/* /usr
- rm -rf cmake-3.3.2-Linux-x86_64
- rm cmake-3.3.2-Linux-x86_64.tar.gz

- export TRAVIS_CXX=$CXX



script:
- bii init -l
- bii configure "-DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
- bii build

after_success:
  # Publish block
- if [[ -n $TRAVIS_TAG ]]; then bii publish -r --tag STABLE --versiontag $TRAVIS_TAG; fi
- if [[ -z $TRAVIS_TAG ]]; then bii publish -r; fi

  # If there are changes, commit them
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
- git add -A .
- git commit -m "$COMMIT_IGNORE_BUILD"
- git remote -v
- git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git
- git push


env:
  global:
  - USER_EMAIL=david.szakallas@gmail.com
  - USER_NAME="Midiparse"
  - COMMIT_IGNORE_BUILD="Promoted version. ***travis***"
  - BLOCK_NAME=sprincle
  - USER=szdavid92
  #BII_PASSWORD
  - secure: "xZ6uqeNopkLJPeFeKmB92XXxv3TMLg3F8ye+5B2NO/YMfP31r4vlRBmWDjGBdiSu2gjuBoxQZeyvBWQ3Qbu5k+Tj4q2nN7V9AChpXneDl1ptMmOS1FcAF+ZGIyHW5BPn8bLxQOA76CEHfdxd2Z8HWt5XkI9aKUtCFtTRxylTS7N0iLaFaGQr6WlIVQHEUmNzc2ZPH8FOBqGNPLLjGnqc6bKlTXj0tSTibzYC64o3Gq4QwIq3Y3dPb2I0PPsLoSgG9szhERL+vqUv7A13uwpm5CwPVd9oBn3dp2Kp0Uj4LCAClwpbTsGqKqXtYqRd4vNLM0QBikJ/vnnqguCL+aLeI5JFQpOIuMScb7sbq4fmSj81YVA+SMm6xpSTK1UKpfSi5kI9kzo/rxbnAqKM08PUsscSvZ19QBNwYMvSAPQKEOl0TYXZ5L7S7shzAeauxTZRubimJqkXR3rV7oUz8TQYc2ZrqXIym846ba4D6fufhg2VAiwRChmo7FQIIUbVDVXrkbwX/gy0Njax7XDReV8fyQWfYc5fOlQkNqGiRoKlUDPjG3MWsnfLdOqaaVyXIY+3nV+cvZMaAcBnbbL5zYjheAM1rsETcnrtTo8qPyEzWk/W/A0jfSTYFX02lOxQwOJGTGNhCp3wzFhjEWr0bx/F45Wn65YbojbOvpa4samRJ0I="
  #GITHUB_TOKEN
  - secure: "prYchnS1W5htdXFDEreNaagyMRHu9asSj4l2oQwdXBcXiUZ65/w3gLPR1jZITACkVc+BcdxP5gM9o0c6FZDUyWgxySNT8mzJROUMOBZp+hNv3guwgEJb+iCOmYLeweLBlD0/Qz8kFfVVPfbPBr6Iip7cow1BLFlK2coBRaz3RGUnXZzMnqazXBzNHcl+lKiyXiT49ES2L3e4T//fzg1L9Au5hEeZlbrsO0mk9JCRXDNn3gP8S1KUUbViCZ/TWNG7OW+V5se/oshTq6ZF+cJKfDu1AlCh3P0MGbDgnRlpOaBjJEg1k6USH8wLH1/YN3tGkp3yirbDpeTNOPbyaor2+o9v/9C7szvJ07qCNfDsmdC3nzG4rkvY7qWepZWFcmVaZ9qMk2OG7IrqoyWb9PdESoSyAQ5oUNmMNBtM3gBv7/Ufi+LiMVMRV2ZRcFuc83brFXM5RNHVOPM4sya0rS8tOGDE9tRiZuqZu8JGP8BWKnvOCm7XNwrpaKfL8y4xdQq480hQqJtP1AqS7CaIujRU089FWTWxYR3HOVvSiW4Wjd/EIs7utfCKnnm44fKei+bGaEl8pXVTzZn5JBM9BEns3hIF5NV4LlmGjF2dF7fgC2Gul5ucZHdQ/JOHVYw5NSb48PpXP7tsKmarRIVCy3Pk7OZhGjUIFOobbqIh2hG1eK4="

